// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientRequest.proto

package com.gxf.udp.proto;

public final class ClientRequestObject_Pb {
  private ClientRequestObject_Pb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetAppByIdParamObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gxf.udp.proto.GetAppByIdParamObject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string appKey = 1;</code>
     */
    String getAppKey();
    /**
     * <code>string appKey = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppKeyBytes();

    /**
     * <code>string clientVersion = 2;</code>
     */
    String getClientVersion();
    /**
     * <code>string clientVersion = 2;</code>
     */
    com.google.protobuf.ByteString
        getClientVersionBytes();

    /**
     * <code>string clientLanguage = 3;</code>
     */
    String getClientLanguage();
    /**
     * <code>string clientLanguage = 3;</code>
     */
    com.google.protobuf.ByteString
        getClientLanguageBytes();
  }
  /**
   * Protobuf type {@code com.gxf.udp.proto.GetAppByIdParamObject}
   */
  public  static final class GetAppByIdParamObject extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gxf.udp.proto.GetAppByIdParamObject)
      GetAppByIdParamObjectOrBuilder {
    // Use GetAppByIdParamObject.newBuilder() to construct.
    private GetAppByIdParamObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetAppByIdParamObject() {
      appKey_ = "";
      clientVersion_ = "";
      clientLanguage_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetAppByIdParamObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              appKey_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              clientVersion_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              clientLanguage_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientRequestObject_Pb.internal_static_com_gxf_udp_proto_GetAppByIdParamObject_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientRequestObject_Pb.internal_static_com_gxf_udp_proto_GetAppByIdParamObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetAppByIdParamObject.class, Builder.class);
    }

    public static final int APPKEY_FIELD_NUMBER = 1;
    private volatile Object appKey_;
    /**
     * <code>string appKey = 1;</code>
     */
    public String getAppKey() {
      Object ref = appKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        appKey_ = s;
        return s;
      }
    }
    /**
     * <code>string appKey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppKeyBytes() {
      Object ref = appKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        appKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTVERSION_FIELD_NUMBER = 2;
    private volatile Object clientVersion_;
    /**
     * <code>string clientVersion = 2;</code>
     */
    public String getClientVersion() {
      Object ref = clientVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string clientVersion = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientVersionBytes() {
      Object ref = clientVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTLANGUAGE_FIELD_NUMBER = 3;
    private volatile Object clientLanguage_;
    /**
     * <code>string clientLanguage = 3;</code>
     */
    public String getClientLanguage() {
      Object ref = clientLanguage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientLanguage_ = s;
        return s;
      }
    }
    /**
     * <code>string clientLanguage = 3;</code>
     */
    public com.google.protobuf.ByteString
        getClientLanguageBytes() {
      Object ref = clientLanguage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientLanguage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAppKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appKey_);
      }
      if (!getClientVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientVersion_);
      }
      if (!getClientLanguageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clientLanguage_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAppKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appKey_);
      }
      if (!getClientVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientVersion_);
      }
      if (!getClientLanguageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clientLanguage_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GetAppByIdParamObject)) {
        return super.equals(obj);
      }
      GetAppByIdParamObject other = (GetAppByIdParamObject) obj;

      boolean result = true;
      result = result && getAppKey()
          .equals(other.getAppKey());
      result = result && getClientVersion()
          .equals(other.getClientVersion());
      result = result && getClientLanguage()
          .equals(other.getClientLanguage());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APPKEY_FIELD_NUMBER;
      hash = (53 * hash) + getAppKey().hashCode();
      hash = (37 * hash) + CLIENTVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getClientVersion().hashCode();
      hash = (37 * hash) + CLIENTLANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getClientLanguage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GetAppByIdParamObject parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetAppByIdParamObject parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetAppByIdParamObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetAppByIdParamObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetAppByIdParamObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetAppByIdParamObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetAppByIdParamObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetAppByIdParamObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetAppByIdParamObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GetAppByIdParamObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetAppByIdParamObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetAppByIdParamObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GetAppByIdParamObject prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gxf.udp.proto.GetAppByIdParamObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gxf.udp.proto.GetAppByIdParamObject)
        GetAppByIdParamObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientRequestObject_Pb.internal_static_com_gxf_udp_proto_GetAppByIdParamObject_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientRequestObject_Pb.internal_static_com_gxf_udp_proto_GetAppByIdParamObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GetAppByIdParamObject.class, Builder.class);
      }

      // Construct using com.gxf.udp.proto.ClientRequestObject_Pb.GetAppByIdParamObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        appKey_ = "";

        clientVersion_ = "";

        clientLanguage_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientRequestObject_Pb.internal_static_com_gxf_udp_proto_GetAppByIdParamObject_descriptor;
      }

      public GetAppByIdParamObject getDefaultInstanceForType() {
        return GetAppByIdParamObject.getDefaultInstance();
      }

      public GetAppByIdParamObject build() {
        GetAppByIdParamObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GetAppByIdParamObject buildPartial() {
        GetAppByIdParamObject result = new GetAppByIdParamObject(this);
        result.appKey_ = appKey_;
        result.clientVersion_ = clientVersion_;
        result.clientLanguage_ = clientLanguage_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GetAppByIdParamObject) {
          return mergeFrom((GetAppByIdParamObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GetAppByIdParamObject other) {
        if (other == GetAppByIdParamObject.getDefaultInstance()) return this;
        if (!other.getAppKey().isEmpty()) {
          appKey_ = other.appKey_;
          onChanged();
        }
        if (!other.getClientVersion().isEmpty()) {
          clientVersion_ = other.clientVersion_;
          onChanged();
        }
        if (!other.getClientLanguage().isEmpty()) {
          clientLanguage_ = other.clientLanguage_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GetAppByIdParamObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GetAppByIdParamObject) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object appKey_ = "";
      /**
       * <code>string appKey = 1;</code>
       */
      public String getAppKey() {
        Object ref = appKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          appKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string appKey = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppKeyBytes() {
        Object ref = appKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          appKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appKey = 1;</code>
       */
      public Builder setAppKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appKey = 1;</code>
       */
      public Builder clearAppKey() {
        
        appKey_ = getDefaultInstance().getAppKey();
        onChanged();
        return this;
      }
      /**
       * <code>string appKey = 1;</code>
       */
      public Builder setAppKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appKey_ = value;
        onChanged();
        return this;
      }

      private Object clientVersion_ = "";
      /**
       * <code>string clientVersion = 2;</code>
       */
      public String getClientVersion() {
        Object ref = clientVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          clientVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string clientVersion = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClientVersionBytes() {
        Object ref = clientVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientVersion = 2;</code>
       */
      public Builder setClientVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientVersion = 2;</code>
       */
      public Builder clearClientVersion() {
        
        clientVersion_ = getDefaultInstance().getClientVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string clientVersion = 2;</code>
       */
      public Builder setClientVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientVersion_ = value;
        onChanged();
        return this;
      }

      private Object clientLanguage_ = "";
      /**
       * <code>string clientLanguage = 3;</code>
       */
      public String getClientLanguage() {
        Object ref = clientLanguage_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          clientLanguage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string clientLanguage = 3;</code>
       */
      public com.google.protobuf.ByteString
          getClientLanguageBytes() {
        Object ref = clientLanguage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientLanguage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientLanguage = 3;</code>
       */
      public Builder setClientLanguage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientLanguage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientLanguage = 3;</code>
       */
      public Builder clearClientLanguage() {
        
        clientLanguage_ = getDefaultInstance().getClientLanguage();
        onChanged();
        return this;
      }
      /**
       * <code>string clientLanguage = 3;</code>
       */
      public Builder setClientLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientLanguage_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.gxf.udp.proto.GetAppByIdParamObject)
    }

    // @@protoc_insertion_point(class_scope:com.gxf.udp.proto.GetAppByIdParamObject)
    private static final GetAppByIdParamObject DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetAppByIdParamObject();
    }

    public static GetAppByIdParamObject getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetAppByIdParamObject>
        PARSER = new com.google.protobuf.AbstractParser<GetAppByIdParamObject>() {
      public GetAppByIdParamObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetAppByIdParamObject(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetAppByIdParamObject> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetAppByIdParamObject> getParserForType() {
      return PARSER;
    }

    public GetAppByIdParamObject getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientReportParamObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gxf.udp.proto.ClientReportParamObject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string clientVersion = 1;</code>
     */
    String getClientVersion();
    /**
     * <code>string clientVersion = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientVersionBytes();

    /**
     * <code>.com.gxf.udp.proto.ClientReportBean reportData = 2;</code>
     */
    boolean hasReportData();
    /**
     * <code>.com.gxf.udp.proto.ClientReportBean reportData = 2;</code>
     */
    ClientReportBean_Pb.ClientReportBean getReportData();
    /**
     * <code>.com.gxf.udp.proto.ClientReportBean reportData = 2;</code>
     */
    ClientReportBean_Pb.ClientReportBeanOrBuilder getReportDataOrBuilder();

    /**
     * <code>string clientLanguage = 3;</code>
     */
    String getClientLanguage();
    /**
     * <code>string clientLanguage = 3;</code>
     */
    com.google.protobuf.ByteString
        getClientLanguageBytes();
  }
  /**
   * Protobuf type {@code com.gxf.udp.proto.ClientReportParamObject}
   */
  public  static final class ClientReportParamObject extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gxf.udp.proto.ClientReportParamObject)
      ClientReportParamObjectOrBuilder {
    // Use ClientReportParamObject.newBuilder() to construct.
    private ClientReportParamObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientReportParamObject() {
      clientVersion_ = "";
      clientLanguage_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ClientReportParamObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              clientVersion_ = s;
              break;
            }
            case 18: {
              ClientReportBean_Pb.ClientReportBean.Builder subBuilder = null;
              if (reportData_ != null) {
                subBuilder = reportData_.toBuilder();
              }
              reportData_ = input.readMessage(ClientReportBean_Pb.ClientReportBean.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(reportData_);
                reportData_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              clientLanguage_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientRequestObject_Pb.internal_static_com_gxf_udp_proto_ClientReportParamObject_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientRequestObject_Pb.internal_static_com_gxf_udp_proto_ClientReportParamObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientReportParamObject.class, Builder.class);
    }

    public static final int CLIENTVERSION_FIELD_NUMBER = 1;
    private volatile Object clientVersion_;
    /**
     * <code>string clientVersion = 1;</code>
     */
    public String getClientVersion() {
      Object ref = clientVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string clientVersion = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientVersionBytes() {
      Object ref = clientVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REPORTDATA_FIELD_NUMBER = 2;
    private ClientReportBean_Pb.ClientReportBean reportData_;
    /**
     * <code>.com.gxf.udp.proto.ClientReportBean reportData = 2;</code>
     */
    public boolean hasReportData() {
      return reportData_ != null;
    }
    /**
     * <code>.com.gxf.udp.proto.ClientReportBean reportData = 2;</code>
     */
    public ClientReportBean_Pb.ClientReportBean getReportData() {
      return reportData_ == null ? ClientReportBean_Pb.ClientReportBean.getDefaultInstance() : reportData_;
    }
    /**
     * <code>.com.gxf.udp.proto.ClientReportBean reportData = 2;</code>
     */
    public ClientReportBean_Pb.ClientReportBeanOrBuilder getReportDataOrBuilder() {
      return getReportData();
    }

    public static final int CLIENTLANGUAGE_FIELD_NUMBER = 3;
    private volatile Object clientLanguage_;
    /**
     * <code>string clientLanguage = 3;</code>
     */
    public String getClientLanguage() {
      Object ref = clientLanguage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientLanguage_ = s;
        return s;
      }
    }
    /**
     * <code>string clientLanguage = 3;</code>
     */
    public com.google.protobuf.ByteString
        getClientLanguageBytes() {
      Object ref = clientLanguage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientLanguage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientVersion_);
      }
      if (reportData_ != null) {
        output.writeMessage(2, getReportData());
      }
      if (!getClientLanguageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clientLanguage_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientVersion_);
      }
      if (reportData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getReportData());
      }
      if (!getClientLanguageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clientLanguage_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ClientReportParamObject)) {
        return super.equals(obj);
      }
      ClientReportParamObject other = (ClientReportParamObject) obj;

      boolean result = true;
      result = result && getClientVersion()
          .equals(other.getClientVersion());
      result = result && (hasReportData() == other.hasReportData());
      if (hasReportData()) {
        result = result && getReportData()
            .equals(other.getReportData());
      }
      result = result && getClientLanguage()
          .equals(other.getClientLanguage());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getClientVersion().hashCode();
      if (hasReportData()) {
        hash = (37 * hash) + REPORTDATA_FIELD_NUMBER;
        hash = (53 * hash) + getReportData().hashCode();
      }
      hash = (37 * hash) + CLIENTLANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getClientLanguage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ClientReportParamObject parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientReportParamObject parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientReportParamObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientReportParamObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientReportParamObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientReportParamObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientReportParamObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClientReportParamObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientReportParamObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ClientReportParamObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientReportParamObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClientReportParamObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ClientReportParamObject prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gxf.udp.proto.ClientReportParamObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gxf.udp.proto.ClientReportParamObject)
        ClientReportParamObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientRequestObject_Pb.internal_static_com_gxf_udp_proto_ClientReportParamObject_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientRequestObject_Pb.internal_static_com_gxf_udp_proto_ClientReportParamObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientReportParamObject.class, Builder.class);
      }

      // Construct using com.gxf.udp.proto.ClientRequestObject_Pb.ClientReportParamObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientVersion_ = "";

        if (reportDataBuilder_ == null) {
          reportData_ = null;
        } else {
          reportData_ = null;
          reportDataBuilder_ = null;
        }
        clientLanguage_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientRequestObject_Pb.internal_static_com_gxf_udp_proto_ClientReportParamObject_descriptor;
      }

      public ClientReportParamObject getDefaultInstanceForType() {
        return ClientReportParamObject.getDefaultInstance();
      }

      public ClientReportParamObject build() {
        ClientReportParamObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ClientReportParamObject buildPartial() {
        ClientReportParamObject result = new ClientReportParamObject(this);
        result.clientVersion_ = clientVersion_;
        if (reportDataBuilder_ == null) {
          result.reportData_ = reportData_;
        } else {
          result.reportData_ = reportDataBuilder_.build();
        }
        result.clientLanguage_ = clientLanguage_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientReportParamObject) {
          return mergeFrom((ClientReportParamObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientReportParamObject other) {
        if (other == ClientReportParamObject.getDefaultInstance()) return this;
        if (!other.getClientVersion().isEmpty()) {
          clientVersion_ = other.clientVersion_;
          onChanged();
        }
        if (other.hasReportData()) {
          mergeReportData(other.getReportData());
        }
        if (!other.getClientLanguage().isEmpty()) {
          clientLanguage_ = other.clientLanguage_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClientReportParamObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClientReportParamObject) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object clientVersion_ = "";
      /**
       * <code>string clientVersion = 1;</code>
       */
      public String getClientVersion() {
        Object ref = clientVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          clientVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string clientVersion = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientVersionBytes() {
        Object ref = clientVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientVersion = 1;</code>
       */
      public Builder setClientVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientVersion = 1;</code>
       */
      public Builder clearClientVersion() {
        
        clientVersion_ = getDefaultInstance().getClientVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string clientVersion = 1;</code>
       */
      public Builder setClientVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientVersion_ = value;
        onChanged();
        return this;
      }

      private ClientReportBean_Pb.ClientReportBean reportData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ClientReportBean_Pb.ClientReportBean, ClientReportBean_Pb.ClientReportBean.Builder, ClientReportBean_Pb.ClientReportBeanOrBuilder> reportDataBuilder_;
      /**
       * <code>.com.gxf.udp.proto.ClientReportBean reportData = 2;</code>
       */
      public boolean hasReportData() {
        return reportDataBuilder_ != null || reportData_ != null;
      }
      /**
       * <code>.com.gxf.udp.proto.ClientReportBean reportData = 2;</code>
       */
      public ClientReportBean_Pb.ClientReportBean getReportData() {
        if (reportDataBuilder_ == null) {
          return reportData_ == null ? ClientReportBean_Pb.ClientReportBean.getDefaultInstance() : reportData_;
        } else {
          return reportDataBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.gxf.udp.proto.ClientReportBean reportData = 2;</code>
       */
      public Builder setReportData(ClientReportBean_Pb.ClientReportBean value) {
        if (reportDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          reportData_ = value;
          onChanged();
        } else {
          reportDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.gxf.udp.proto.ClientReportBean reportData = 2;</code>
       */
      public Builder setReportData(
          ClientReportBean_Pb.ClientReportBean.Builder builderForValue) {
        if (reportDataBuilder_ == null) {
          reportData_ = builderForValue.build();
          onChanged();
        } else {
          reportDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.gxf.udp.proto.ClientReportBean reportData = 2;</code>
       */
      public Builder mergeReportData(ClientReportBean_Pb.ClientReportBean value) {
        if (reportDataBuilder_ == null) {
          if (reportData_ != null) {
            reportData_ =
              ClientReportBean_Pb.ClientReportBean.newBuilder(reportData_).mergeFrom(value).buildPartial();
          } else {
            reportData_ = value;
          }
          onChanged();
        } else {
          reportDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.gxf.udp.proto.ClientReportBean reportData = 2;</code>
       */
      public Builder clearReportData() {
        if (reportDataBuilder_ == null) {
          reportData_ = null;
          onChanged();
        } else {
          reportData_ = null;
          reportDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.gxf.udp.proto.ClientReportBean reportData = 2;</code>
       */
      public ClientReportBean_Pb.ClientReportBean.Builder getReportDataBuilder() {
        
        onChanged();
        return getReportDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.gxf.udp.proto.ClientReportBean reportData = 2;</code>
       */
      public ClientReportBean_Pb.ClientReportBeanOrBuilder getReportDataOrBuilder() {
        if (reportDataBuilder_ != null) {
          return reportDataBuilder_.getMessageOrBuilder();
        } else {
          return reportData_ == null ?
              ClientReportBean_Pb.ClientReportBean.getDefaultInstance() : reportData_;
        }
      }
      /**
       * <code>.com.gxf.udp.proto.ClientReportBean reportData = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ClientReportBean_Pb.ClientReportBean, ClientReportBean_Pb.ClientReportBean.Builder, ClientReportBean_Pb.ClientReportBeanOrBuilder>
          getReportDataFieldBuilder() {
        if (reportDataBuilder_ == null) {
          reportDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ClientReportBean_Pb.ClientReportBean, ClientReportBean_Pb.ClientReportBean.Builder, ClientReportBean_Pb.ClientReportBeanOrBuilder>(
                  getReportData(),
                  getParentForChildren(),
                  isClean());
          reportData_ = null;
        }
        return reportDataBuilder_;
      }

      private Object clientLanguage_ = "";
      /**
       * <code>string clientLanguage = 3;</code>
       */
      public String getClientLanguage() {
        Object ref = clientLanguage_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          clientLanguage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string clientLanguage = 3;</code>
       */
      public com.google.protobuf.ByteString
          getClientLanguageBytes() {
        Object ref = clientLanguage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientLanguage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientLanguage = 3;</code>
       */
      public Builder setClientLanguage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientLanguage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientLanguage = 3;</code>
       */
      public Builder clearClientLanguage() {
        
        clientLanguage_ = getDefaultInstance().getClientLanguage();
        onChanged();
        return this;
      }
      /**
       * <code>string clientLanguage = 3;</code>
       */
      public Builder setClientLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientLanguage_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.gxf.udp.proto.ClientReportParamObject)
    }

    // @@protoc_insertion_point(class_scope:com.gxf.udp.proto.ClientReportParamObject)
    private static final ClientReportParamObject DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ClientReportParamObject();
    }

    public static ClientReportParamObject getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientReportParamObject>
        PARSER = new com.google.protobuf.AbstractParser<ClientReportParamObject>() {
      public ClientReportParamObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ClientReportParamObject(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientReportParamObject> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ClientReportParamObject> getParserForType() {
      return PARSER;
    }

    public ClientReportParamObject getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gxf_udp_proto_GetAppByIdParamObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gxf_udp_proto_GetAppByIdParamObject_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gxf_udp_proto_ClientReportParamObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gxf_udp_proto_ClientReportParamObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023ClientRequest.proto\022\021com.gxf.udp.proto" +
      "\032\022ClientReport.proto\"V\n\025GetAppByIdParamO" +
      "bject\022\016\n\006appKey\030\001 \001(\t\022\025\n\rclientVersion\030\002" +
      " \001(\t\022\026\n\016clientLanguage\030\003 \001(\t\"\201\001\n\027ClientR" +
      "eportParamObject\022\025\n\rclientVersion\030\001 \001(\t\022" +
      "7\n\nreportData\030\002 \001(\0132#.com.gxf.udp.proto." +
      "ClientReportBean\022\026\n\016clientLanguage\030\003 \001(\t" +
      "B\030B\026ClientRequestObject_Pbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ClientReportBean_Pb.getDescriptor(),
        }, assigner);
    internal_static_com_gxf_udp_proto_GetAppByIdParamObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gxf_udp_proto_GetAppByIdParamObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gxf_udp_proto_GetAppByIdParamObject_descriptor,
        new String[] { "AppKey", "ClientVersion", "ClientLanguage", });
    internal_static_com_gxf_udp_proto_ClientReportParamObject_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gxf_udp_proto_ClientReportParamObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gxf_udp_proto_ClientReportParamObject_descriptor,
        new String[] { "ClientVersion", "ReportData", "ClientLanguage", });
    ClientReportBean_Pb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
