// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UDPServerObject.proto

package com.gxf.udp.proto;

public final class UDPServerObject_Pb {
  private UDPServerObject_Pb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UDPServerObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gxf.udp.proto.UDPServerObject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 sessionID = 1;</code>
     */
    int getSessionID();

    /**
     * <code>bytes result = 2;</code>
     */
    com.google.protobuf.ByteString getResult();

    /**
     * <pre>
     *1 success 2 fail
     * </pre>
     *
     * <code>int32 resultCode = 3;</code>
     */
    int getResultCode();
  }
  /**
   * <pre>
   *udp server return object
   * </pre>
   *
   * Protobuf type {@code com.gxf.udp.proto.UDPServerObject}
   */
  public  static final class UDPServerObject extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gxf.udp.proto.UDPServerObject)
      UDPServerObjectOrBuilder {
    // Use UDPServerObject.newBuilder() to construct.
    private UDPServerObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UDPServerObject() {
      sessionID_ = 0;
      result_ = com.google.protobuf.ByteString.EMPTY;
      resultCode_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UDPServerObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              sessionID_ = input.readInt32();
              break;
            }
            case 18: {

              result_ = input.readBytes();
              break;
            }
            case 24: {

              resultCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UDPServerObject_Pb.internal_static_com_gxf_udp_proto_UDPServerObject_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UDPServerObject_Pb.internal_static_com_gxf_udp_proto_UDPServerObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UDPServerObject.class, Builder.class);
    }

    public static final int SESSIONID_FIELD_NUMBER = 1;
    private int sessionID_;
    /**
     * <code>int32 sessionID = 1;</code>
     */
    public int getSessionID() {
      return sessionID_;
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString result_;
    /**
     * <code>bytes result = 2;</code>
     */
    public com.google.protobuf.ByteString getResult() {
      return result_;
    }

    public static final int RESULTCODE_FIELD_NUMBER = 3;
    private int resultCode_;
    /**
     * <pre>
     *1 success 2 fail
     * </pre>
     *
     * <code>int32 resultCode = 3;</code>
     */
    public int getResultCode() {
      return resultCode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sessionID_ != 0) {
        output.writeInt32(1, sessionID_);
      }
      if (!result_.isEmpty()) {
        output.writeBytes(2, result_);
      }
      if (resultCode_ != 0) {
        output.writeInt32(3, resultCode_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sessionID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sessionID_);
      }
      if (!result_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, result_);
      }
      if (resultCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, resultCode_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UDPServerObject)) {
        return super.equals(obj);
      }
      UDPServerObject other = (UDPServerObject) obj;

      boolean result = true;
      result = result && (getSessionID()
          == other.getSessionID());
      result = result && getResult()
          .equals(other.getResult());
      result = result && (getResultCode()
          == other.getResultCode());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionID();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
      hash = (37 * hash) + RESULTCODE_FIELD_NUMBER;
      hash = (53 * hash) + getResultCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UDPServerObject parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UDPServerObject parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UDPServerObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UDPServerObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UDPServerObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UDPServerObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UDPServerObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UDPServerObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UDPServerObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UDPServerObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UDPServerObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UDPServerObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UDPServerObject prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *udp server return object
     * </pre>
     *
     * Protobuf type {@code com.gxf.udp.proto.UDPServerObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gxf.udp.proto.UDPServerObject)
        UDPServerObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UDPServerObject_Pb.internal_static_com_gxf_udp_proto_UDPServerObject_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UDPServerObject_Pb.internal_static_com_gxf_udp_proto_UDPServerObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UDPServerObject.class, Builder.class);
      }

      // Construct using com.gxf.udp.proto.UDPServerObject_Pb.UDPServerObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sessionID_ = 0;

        result_ = com.google.protobuf.ByteString.EMPTY;

        resultCode_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UDPServerObject_Pb.internal_static_com_gxf_udp_proto_UDPServerObject_descriptor;
      }

      public UDPServerObject getDefaultInstanceForType() {
        return UDPServerObject.getDefaultInstance();
      }

      public UDPServerObject build() {
        UDPServerObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public UDPServerObject buildPartial() {
        UDPServerObject result = new UDPServerObject(this);
        result.sessionID_ = sessionID_;
        result.result_ = result_;
        result.resultCode_ = resultCode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UDPServerObject) {
          return mergeFrom((UDPServerObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UDPServerObject other) {
        if (other == UDPServerObject.getDefaultInstance()) return this;
        if (other.getSessionID() != 0) {
          setSessionID(other.getSessionID());
        }
        if (other.getResult() != com.google.protobuf.ByteString.EMPTY) {
          setResult(other.getResult());
        }
        if (other.getResultCode() != 0) {
          setResultCode(other.getResultCode());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UDPServerObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UDPServerObject) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int sessionID_ ;
      /**
       * <code>int32 sessionID = 1;</code>
       */
      public int getSessionID() {
        return sessionID_;
      }
      /**
       * <code>int32 sessionID = 1;</code>
       */
      public Builder setSessionID(int value) {
        
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sessionID = 1;</code>
       */
      public Builder clearSessionID() {
        
        sessionID_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString result_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes result = 2;</code>
       */
      public com.google.protobuf.ByteString getResult() {
        return result_;
      }
      /**
       * <code>bytes result = 2;</code>
       */
      public Builder setResult(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes result = 2;</code>
       */
      public Builder clearResult() {
        
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }

      private int resultCode_ ;
      /**
       * <pre>
       *1 success 2 fail
       * </pre>
       *
       * <code>int32 resultCode = 3;</code>
       */
      public int getResultCode() {
        return resultCode_;
      }
      /**
       * <pre>
       *1 success 2 fail
       * </pre>
       *
       * <code>int32 resultCode = 3;</code>
       */
      public Builder setResultCode(int value) {
        
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1 success 2 fail
       * </pre>
       *
       * <code>int32 resultCode = 3;</code>
       */
      public Builder clearResultCode() {
        
        resultCode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.gxf.udp.proto.UDPServerObject)
    }

    // @@protoc_insertion_point(class_scope:com.gxf.udp.proto.UDPServerObject)
    private static final UDPServerObject DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UDPServerObject();
    }

    public static UDPServerObject getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UDPServerObject>
        PARSER = new com.google.protobuf.AbstractParser<UDPServerObject>() {
      public UDPServerObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UDPServerObject(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UDPServerObject> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UDPServerObject> getParserForType() {
      return PARSER;
    }

    public UDPServerObject getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gxf_udp_proto_UDPServerObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gxf_udp_proto_UDPServerObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025UDPServerObject.proto\022\021com.gxf.udp.pro" +
      "to\"H\n\017UDPServerObject\022\021\n\tsessionID\030\001 \001(\005" +
      "\022\016\n\006result\030\002 \001(\014\022\022\n\nresultCode\030\003 \001(\005B\024B\022" +
      "UDPServerObject_Pbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_gxf_udp_proto_UDPServerObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gxf_udp_proto_UDPServerObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gxf_udp_proto_UDPServerObject_descriptor,
        new String[] { "SessionID", "Result", "ResultCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
