// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeartbeatInfo.proto

package com.gxf.udp.proto;

public final class HeartbeatInfo_Pb {
  private HeartbeatInfo_Pb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeartBeatInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gxf.udp.proto.HeartBeatInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string appKey = 1;</code>
     */
    java.lang.String getAppKey();
    /**
     * <code>string appKey = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppKeyBytes();

    /**
     * <code>int32 shardNum = 2;</code>
     */
    int getShardNum();

    /**
     * <code>string shardInfo = 3;</code>
     */
    java.lang.String getShardInfo();
    /**
     * <code>string shardInfo = 3;</code>
     */
    com.google.protobuf.ByteString
        getShardInfoBytes();

    /**
     * <code>string sentinels = 4;</code>
     */
    java.lang.String getSentinels();
    /**
     * <code>string sentinels = 4;</code>
     */
    com.google.protobuf.ByteString
        getSentinelsBytes();

    /**
     * <code>string masterName = 5;</code>
     */
    java.lang.String getMasterName();
    /**
     * <code>string masterName = 5;</code>
     */
    com.google.protobuf.ByteString
        getMasterNameBytes();

    /**
     * <code>string standalone = 6;</code>
     */
    java.lang.String getStandalone();
    /**
     * <code>string standalone = 6;</code>
     */
    com.google.protobuf.ByteString
        getStandaloneBytes();

    /**
     * <code>int32 status = 7;</code>
     */
    int getStatus();

    /**
     * <code>string msg = 8;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 8;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>string reportIp = 9;</code>
     */
    java.lang.String getReportIp();
    /**
     * <code>string reportIp = 9;</code>
     */
    com.google.protobuf.ByteString
        getReportIpBytes();

    /**
     * <code>int32 type = 10;</code>
     */
    int getType();

    /**
     * <code>string password = 11;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 11;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>string proxyAddrs = 12;</code>
     */
    java.lang.String getProxyAddrs();
    /**
     * <code>string proxyAddrs = 12;</code>
     */
    com.google.protobuf.ByteString
        getProxyAddrsBytes();
  }
  /**
   * Protobuf type {@code com.gxf.udp.proto.HeartBeatInfo}
   */
  public  static final class HeartBeatInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gxf.udp.proto.HeartBeatInfo)
      HeartBeatInfoOrBuilder {
    // Use HeartBeatInfo.newBuilder() to construct.
    private HeartBeatInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeatInfo() {
      appKey_ = "";
      shardNum_ = 0;
      shardInfo_ = "";
      sentinels_ = "";
      masterName_ = "";
      standalone_ = "";
      status_ = 0;
      msg_ = "";
      reportIp_ = "";
      type_ = 0;
      password_ = "";
      proxyAddrs_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HeartBeatInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              appKey_ = s;
              break;
            }
            case 16: {

              shardNum_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              shardInfo_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              sentinels_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              masterName_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              standalone_ = s;
              break;
            }
            case 56: {

              status_ = input.readInt32();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              reportIp_ = s;
              break;
            }
            case 80: {

              type_ = input.readInt32();
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              proxyAddrs_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gxf.udp.proto.HeartbeatInfo_Pb.internal_static_com_gxf_udp_proto_HeartBeatInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gxf.udp.proto.HeartbeatInfo_Pb.internal_static_com_gxf_udp_proto_HeartBeatInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo.class, com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo.Builder.class);
    }

    public static final int APPKEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object appKey_;
    /**
     * <code>string appKey = 1;</code>
     */
    public java.lang.String getAppKey() {
      java.lang.Object ref = appKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appKey_ = s;
        return s;
      }
    }
    /**
     * <code>string appKey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppKeyBytes() {
      java.lang.Object ref = appKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHARDNUM_FIELD_NUMBER = 2;
    private int shardNum_;
    /**
     * <code>int32 shardNum = 2;</code>
     */
    public int getShardNum() {
      return shardNum_;
    }

    public static final int SHARDINFO_FIELD_NUMBER = 3;
    private volatile java.lang.Object shardInfo_;
    /**
     * <code>string shardInfo = 3;</code>
     */
    public java.lang.String getShardInfo() {
      java.lang.Object ref = shardInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shardInfo_ = s;
        return s;
      }
    }
    /**
     * <code>string shardInfo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getShardInfoBytes() {
      java.lang.Object ref = shardInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shardInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENTINELS_FIELD_NUMBER = 4;
    private volatile java.lang.Object sentinels_;
    /**
     * <code>string sentinels = 4;</code>
     */
    public java.lang.String getSentinels() {
      java.lang.Object ref = sentinels_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sentinels_ = s;
        return s;
      }
    }
    /**
     * <code>string sentinels = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSentinelsBytes() {
      java.lang.Object ref = sentinels_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sentinels_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MASTERNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object masterName_;
    /**
     * <code>string masterName = 5;</code>
     */
    public java.lang.String getMasterName() {
      java.lang.Object ref = masterName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        masterName_ = s;
        return s;
      }
    }
    /**
     * <code>string masterName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMasterNameBytes() {
      java.lang.Object ref = masterName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        masterName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STANDALONE_FIELD_NUMBER = 6;
    private volatile java.lang.Object standalone_;
    /**
     * <code>string standalone = 6;</code>
     */
    public java.lang.String getStandalone() {
      java.lang.Object ref = standalone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        standalone_ = s;
        return s;
      }
    }
    /**
     * <code>string standalone = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStandaloneBytes() {
      java.lang.Object ref = standalone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        standalone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 7;
    private int status_;
    /**
     * <code>int32 status = 7;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int MSG_FIELD_NUMBER = 8;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 8;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 8;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REPORTIP_FIELD_NUMBER = 9;
    private volatile java.lang.Object reportIp_;
    /**
     * <code>string reportIp = 9;</code>
     */
    public java.lang.String getReportIp() {
      java.lang.Object ref = reportIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reportIp_ = s;
        return s;
      }
    }
    /**
     * <code>string reportIp = 9;</code>
     */
    public com.google.protobuf.ByteString
        getReportIpBytes() {
      java.lang.Object ref = reportIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reportIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 10;
    private int type_;
    /**
     * <code>int32 type = 10;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int PASSWORD_FIELD_NUMBER = 11;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 11;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 11;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROXYADDRS_FIELD_NUMBER = 12;
    private volatile java.lang.Object proxyAddrs_;
    /**
     * <code>string proxyAddrs = 12;</code>
     */
    public java.lang.String getProxyAddrs() {
      java.lang.Object ref = proxyAddrs_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        proxyAddrs_ = s;
        return s;
      }
    }
    /**
     * <code>string proxyAddrs = 12;</code>
     */
    public com.google.protobuf.ByteString
        getProxyAddrsBytes() {
      java.lang.Object ref = proxyAddrs_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proxyAddrs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAppKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appKey_);
      }
      if (shardNum_ != 0) {
        output.writeInt32(2, shardNum_);
      }
      if (!getShardInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, shardInfo_);
      }
      if (!getSentinelsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sentinels_);
      }
      if (!getMasterNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, masterName_);
      }
      if (!getStandaloneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, standalone_);
      }
      if (status_ != 0) {
        output.writeInt32(7, status_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, msg_);
      }
      if (!getReportIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, reportIp_);
      }
      if (type_ != 0) {
        output.writeInt32(10, type_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, password_);
      }
      if (!getProxyAddrsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, proxyAddrs_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAppKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appKey_);
      }
      if (shardNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, shardNum_);
      }
      if (!getShardInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, shardInfo_);
      }
      if (!getSentinelsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sentinels_);
      }
      if (!getMasterNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, masterName_);
      }
      if (!getStandaloneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, standalone_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, status_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, msg_);
      }
      if (!getReportIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, reportIp_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, type_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, password_);
      }
      if (!getProxyAddrsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, proxyAddrs_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo)) {
        return super.equals(obj);
      }
      com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo other = (com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo) obj;

      boolean result = true;
      result = result && getAppKey()
          .equals(other.getAppKey());
      result = result && (getShardNum()
          == other.getShardNum());
      result = result && getShardInfo()
          .equals(other.getShardInfo());
      result = result && getSentinels()
          .equals(other.getSentinels());
      result = result && getMasterName()
          .equals(other.getMasterName());
      result = result && getStandalone()
          .equals(other.getStandalone());
      result = result && (getStatus()
          == other.getStatus());
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && getReportIp()
          .equals(other.getReportIp());
      result = result && (getType()
          == other.getType());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && getProxyAddrs()
          .equals(other.getProxyAddrs());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APPKEY_FIELD_NUMBER;
      hash = (53 * hash) + getAppKey().hashCode();
      hash = (37 * hash) + SHARDNUM_FIELD_NUMBER;
      hash = (53 * hash) + getShardNum();
      hash = (37 * hash) + SHARDINFO_FIELD_NUMBER;
      hash = (53 * hash) + getShardInfo().hashCode();
      hash = (37 * hash) + SENTINELS_FIELD_NUMBER;
      hash = (53 * hash) + getSentinels().hashCode();
      hash = (37 * hash) + MASTERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMasterName().hashCode();
      hash = (37 * hash) + STANDALONE_FIELD_NUMBER;
      hash = (53 * hash) + getStandalone().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + REPORTIP_FIELD_NUMBER;
      hash = (53 * hash) + getReportIp().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + PROXYADDRS_FIELD_NUMBER;
      hash = (53 * hash) + getProxyAddrs().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gxf.udp.proto.HeartBeatInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gxf.udp.proto.HeartBeatInfo)
        com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gxf.udp.proto.HeartbeatInfo_Pb.internal_static_com_gxf_udp_proto_HeartBeatInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gxf.udp.proto.HeartbeatInfo_Pb.internal_static_com_gxf_udp_proto_HeartBeatInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo.class, com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo.Builder.class);
      }

      // Construct using com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        appKey_ = "";

        shardNum_ = 0;

        shardInfo_ = "";

        sentinels_ = "";

        masterName_ = "";

        standalone_ = "";

        status_ = 0;

        msg_ = "";

        reportIp_ = "";

        type_ = 0;

        password_ = "";

        proxyAddrs_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gxf.udp.proto.HeartbeatInfo_Pb.internal_static_com_gxf_udp_proto_HeartBeatInfo_descriptor;
      }

      public com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo getDefaultInstanceForType() {
        return com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo.getDefaultInstance();
      }

      public com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo build() {
        com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo buildPartial() {
        com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo result = new com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo(this);
        result.appKey_ = appKey_;
        result.shardNum_ = shardNum_;
        result.shardInfo_ = shardInfo_;
        result.sentinels_ = sentinels_;
        result.masterName_ = masterName_;
        result.standalone_ = standalone_;
        result.status_ = status_;
        result.msg_ = msg_;
        result.reportIp_ = reportIp_;
        result.type_ = type_;
        result.password_ = password_;
        result.proxyAddrs_ = proxyAddrs_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo) {
          return mergeFrom((com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo other) {
        if (other == com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo.getDefaultInstance()) return this;
        if (!other.getAppKey().isEmpty()) {
          appKey_ = other.appKey_;
          onChanged();
        }
        if (other.getShardNum() != 0) {
          setShardNum(other.getShardNum());
        }
        if (!other.getShardInfo().isEmpty()) {
          shardInfo_ = other.shardInfo_;
          onChanged();
        }
        if (!other.getSentinels().isEmpty()) {
          sentinels_ = other.sentinels_;
          onChanged();
        }
        if (!other.getMasterName().isEmpty()) {
          masterName_ = other.masterName_;
          onChanged();
        }
        if (!other.getStandalone().isEmpty()) {
          standalone_ = other.standalone_;
          onChanged();
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (!other.getReportIp().isEmpty()) {
          reportIp_ = other.reportIp_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (!other.getProxyAddrs().isEmpty()) {
          proxyAddrs_ = other.proxyAddrs_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object appKey_ = "";
      /**
       * <code>string appKey = 1;</code>
       */
      public java.lang.String getAppKey() {
        java.lang.Object ref = appKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string appKey = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppKeyBytes() {
        java.lang.Object ref = appKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appKey = 1;</code>
       */
      public Builder setAppKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appKey = 1;</code>
       */
      public Builder clearAppKey() {
        
        appKey_ = getDefaultInstance().getAppKey();
        onChanged();
        return this;
      }
      /**
       * <code>string appKey = 1;</code>
       */
      public Builder setAppKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appKey_ = value;
        onChanged();
        return this;
      }

      private int shardNum_ ;
      /**
       * <code>int32 shardNum = 2;</code>
       */
      public int getShardNum() {
        return shardNum_;
      }
      /**
       * <code>int32 shardNum = 2;</code>
       */
      public Builder setShardNum(int value) {
        
        shardNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 shardNum = 2;</code>
       */
      public Builder clearShardNum() {
        
        shardNum_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object shardInfo_ = "";
      /**
       * <code>string shardInfo = 3;</code>
       */
      public java.lang.String getShardInfo() {
        java.lang.Object ref = shardInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          shardInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string shardInfo = 3;</code>
       */
      public com.google.protobuf.ByteString
          getShardInfoBytes() {
        java.lang.Object ref = shardInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shardInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string shardInfo = 3;</code>
       */
      public Builder setShardInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shardInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string shardInfo = 3;</code>
       */
      public Builder clearShardInfo() {
        
        shardInfo_ = getDefaultInstance().getShardInfo();
        onChanged();
        return this;
      }
      /**
       * <code>string shardInfo = 3;</code>
       */
      public Builder setShardInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        shardInfo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sentinels_ = "";
      /**
       * <code>string sentinels = 4;</code>
       */
      public java.lang.String getSentinels() {
        java.lang.Object ref = sentinels_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sentinels_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sentinels = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSentinelsBytes() {
        java.lang.Object ref = sentinels_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sentinels_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sentinels = 4;</code>
       */
      public Builder setSentinels(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sentinels_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sentinels = 4;</code>
       */
      public Builder clearSentinels() {
        
        sentinels_ = getDefaultInstance().getSentinels();
        onChanged();
        return this;
      }
      /**
       * <code>string sentinels = 4;</code>
       */
      public Builder setSentinelsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sentinels_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object masterName_ = "";
      /**
       * <code>string masterName = 5;</code>
       */
      public java.lang.String getMasterName() {
        java.lang.Object ref = masterName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          masterName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string masterName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMasterNameBytes() {
        java.lang.Object ref = masterName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          masterName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string masterName = 5;</code>
       */
      public Builder setMasterName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        masterName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string masterName = 5;</code>
       */
      public Builder clearMasterName() {
        
        masterName_ = getDefaultInstance().getMasterName();
        onChanged();
        return this;
      }
      /**
       * <code>string masterName = 5;</code>
       */
      public Builder setMasterNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        masterName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object standalone_ = "";
      /**
       * <code>string standalone = 6;</code>
       */
      public java.lang.String getStandalone() {
        java.lang.Object ref = standalone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          standalone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string standalone = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStandaloneBytes() {
        java.lang.Object ref = standalone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          standalone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string standalone = 6;</code>
       */
      public Builder setStandalone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        standalone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string standalone = 6;</code>
       */
      public Builder clearStandalone() {
        
        standalone_ = getDefaultInstance().getStandalone();
        onChanged();
        return this;
      }
      /**
       * <code>string standalone = 6;</code>
       */
      public Builder setStandaloneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        standalone_ = value;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 7;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 7;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 7;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 8;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 8;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 8;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 8;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 8;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reportIp_ = "";
      /**
       * <code>string reportIp = 9;</code>
       */
      public java.lang.String getReportIp() {
        java.lang.Object ref = reportIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reportIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reportIp = 9;</code>
       */
      public com.google.protobuf.ByteString
          getReportIpBytes() {
        java.lang.Object ref = reportIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reportIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reportIp = 9;</code>
       */
      public Builder setReportIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reportIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reportIp = 9;</code>
       */
      public Builder clearReportIp() {
        
        reportIp_ = getDefaultInstance().getReportIp();
        onChanged();
        return this;
      }
      /**
       * <code>string reportIp = 9;</code>
       */
      public Builder setReportIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reportIp_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 10;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 10;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 10;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 11;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 11;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 11;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 11;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 11;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object proxyAddrs_ = "";
      /**
       * <code>string proxyAddrs = 12;</code>
       */
      public java.lang.String getProxyAddrs() {
        java.lang.Object ref = proxyAddrs_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          proxyAddrs_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string proxyAddrs = 12;</code>
       */
      public com.google.protobuf.ByteString
          getProxyAddrsBytes() {
        java.lang.Object ref = proxyAddrs_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          proxyAddrs_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string proxyAddrs = 12;</code>
       */
      public Builder setProxyAddrs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        proxyAddrs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string proxyAddrs = 12;</code>
       */
      public Builder clearProxyAddrs() {
        
        proxyAddrs_ = getDefaultInstance().getProxyAddrs();
        onChanged();
        return this;
      }
      /**
       * <code>string proxyAddrs = 12;</code>
       */
      public Builder setProxyAddrsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        proxyAddrs_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.gxf.udp.proto.HeartBeatInfo)
    }

    // @@protoc_insertion_point(class_scope:com.gxf.udp.proto.HeartBeatInfo)
    private static final com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo();
    }

    public static com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartBeatInfo>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeatInfo>() {
      public HeartBeatInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HeartBeatInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeatInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatInfo> getParserForType() {
      return PARSER;
    }

    public com.gxf.udp.proto.HeartbeatInfo_Pb.HeartBeatInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gxf_udp_proto_HeartBeatInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gxf_udp_proto_HeartBeatInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023HeartbeatInfo.proto\022\021com.gxf.udp.proto" +
      "\"\342\001\n\rHeartBeatInfo\022\016\n\006appKey\030\001 \001(\t\022\020\n\010sh" +
      "ardNum\030\002 \001(\005\022\021\n\tshardInfo\030\003 \001(\t\022\021\n\tsenti" +
      "nels\030\004 \001(\t\022\022\n\nmasterName\030\005 \001(\t\022\022\n\nstanda" +
      "lone\030\006 \001(\t\022\016\n\006status\030\007 \001(\005\022\013\n\003msg\030\010 \001(\t\022" +
      "\020\n\010reportIp\030\t \001(\t\022\014\n\004type\030\n \001(\005\022\020\n\010passw" +
      "ord\030\013 \001(\t\022\022\n\nproxyAddrs\030\014 \001(\tB\022B\020Heartbe" +
      "atInfo_Pbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_gxf_udp_proto_HeartBeatInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gxf_udp_proto_HeartBeatInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gxf_udp_proto_HeartBeatInfo_descriptor,
        new java.lang.String[] { "AppKey", "ShardNum", "ShardInfo", "Sentinels", "MasterName", "Standalone", "Status", "Msg", "ReportIp", "Type", "Password", "ProxyAddrs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
