// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MachineStat.proto

package com.gxf.udp.proto;

public final class MachineStat_Pb {
  private MachineStat_Pb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MachineStatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gxf.udp.proto.MachineStat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>int64 hostId = 2;</code>
     */
    long getHostId();

    /**
     * <code>string ip = 3;</code>
     */
    java.lang.String getIp();
    /**
     * <code>string ip = 3;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>string cpuUsage = 4;</code>
     */
    java.lang.String getCpuUsage();
    /**
     * <code>string cpuUsage = 4;</code>
     */
    com.google.protobuf.ByteString
        getCpuUsageBytes();

    /**
     * <code>string load = 5;</code>
     */
    java.lang.String getLoad();
    /**
     * <code>string load = 5;</code>
     */
    com.google.protobuf.ByteString
        getLoadBytes();

    /**
     * <code>string traffic = 6;</code>
     */
    java.lang.String getTraffic();
    /**
     * <code>string traffic = 6;</code>
     */
    com.google.protobuf.ByteString
        getTrafficBytes();

    /**
     * <code>string memoryUsageRatio = 7;</code>
     */
    java.lang.String getMemoryUsageRatio();
    /**
     * <code>string memoryUsageRatio = 7;</code>
     */
    com.google.protobuf.ByteString
        getMemoryUsageRatioBytes();

    /**
     * <code>string memoryFree = 8;</code>
     */
    java.lang.String getMemoryFree();
    /**
     * <code>string memoryFree = 8;</code>
     */
    com.google.protobuf.ByteString
        getMemoryFreeBytes();

    /**
     * <code>int32 memoryAllocated = 9;</code>
     */
    int getMemoryAllocated();

    /**
     * <code>string memoryTotal = 10;</code>
     */
    java.lang.String getMemoryTotal();
    /**
     * <code>string memoryTotal = 10;</code>
     */
    com.google.protobuf.ByteString
        getMemoryTotalBytes();

    /**
     * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
     */
    java.util.List<com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry> 
        getDisUsageMapList();
    /**
     * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
     */
    com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry getDisUsageMap(int index);
    /**
     * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
     */
    int getDisUsageMapCount();
    /**
     * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
     */
    java.util.List<? extends com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntryOrBuilder> 
        getDisUsageMapOrBuilderList();
    /**
     * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
     */
    com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntryOrBuilder getDisUsageMapOrBuilder(
        int index);

    /**
     * <code>int64 createTime = 12;</code>
     */
    long getCreateTime();

    /**
     * <code>int64 modifyTime = 13;</code>
     */
    long getModifyTime();
  }
  /**
   * Protobuf type {@code com.gxf.udp.proto.MachineStat}
   */
  public  static final class MachineStat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gxf.udp.proto.MachineStat)
      MachineStatOrBuilder {
    // Use MachineStat.newBuilder() to construct.
    private MachineStat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MachineStat() {
      id_ = 0L;
      hostId_ = 0L;
      ip_ = "";
      cpuUsage_ = "";
      load_ = "";
      traffic_ = "";
      memoryUsageRatio_ = "";
      memoryFree_ = "";
      memoryAllocated_ = 0;
      memoryTotal_ = "";
      disUsageMap_ = java.util.Collections.emptyList();
      createTime_ = 0L;
      modifyTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MachineStat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              hostId_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              cpuUsage_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              load_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              traffic_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              memoryUsageRatio_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              memoryFree_ = s;
              break;
            }
            case 72: {

              memoryAllocated_ = input.readInt32();
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              memoryTotal_ = s;
              break;
            }
            case 90: {
              if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
                disUsageMap_ = new java.util.ArrayList<com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry>();
                mutable_bitField0_ |= 0x00000400;
              }
              disUsageMap_.add(
                  input.readMessage(com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.parser(), extensionRegistry));
              break;
            }
            case 96: {

              createTime_ = input.readInt64();
              break;
            }
            case 104: {

              modifyTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
          disUsageMap_ = java.util.Collections.unmodifiableList(disUsageMap_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gxf.udp.proto.MachineStat_Pb.internal_static_com_gxf_udp_proto_MachineStat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gxf.udp.proto.MachineStat_Pb.internal_static_com_gxf_udp_proto_MachineStat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gxf.udp.proto.MachineStat_Pb.MachineStat.class, com.gxf.udp.proto.MachineStat_Pb.MachineStat.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int HOSTID_FIELD_NUMBER = 2;
    private long hostId_;
    /**
     * <code>int64 hostId = 2;</code>
     */
    public long getHostId() {
      return hostId_;
    }

    public static final int IP_FIELD_NUMBER = 3;
    private volatile java.lang.Object ip_;
    /**
     * <code>string ip = 3;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CPUUSAGE_FIELD_NUMBER = 4;
    private volatile java.lang.Object cpuUsage_;
    /**
     * <code>string cpuUsage = 4;</code>
     */
    public java.lang.String getCpuUsage() {
      java.lang.Object ref = cpuUsage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cpuUsage_ = s;
        return s;
      }
    }
    /**
     * <code>string cpuUsage = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCpuUsageBytes() {
      java.lang.Object ref = cpuUsage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cpuUsage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOAD_FIELD_NUMBER = 5;
    private volatile java.lang.Object load_;
    /**
     * <code>string load = 5;</code>
     */
    public java.lang.String getLoad() {
      java.lang.Object ref = load_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        load_ = s;
        return s;
      }
    }
    /**
     * <code>string load = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLoadBytes() {
      java.lang.Object ref = load_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        load_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRAFFIC_FIELD_NUMBER = 6;
    private volatile java.lang.Object traffic_;
    /**
     * <code>string traffic = 6;</code>
     */
    public java.lang.String getTraffic() {
      java.lang.Object ref = traffic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traffic_ = s;
        return s;
      }
    }
    /**
     * <code>string traffic = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTrafficBytes() {
      java.lang.Object ref = traffic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traffic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMORYUSAGERATIO_FIELD_NUMBER = 7;
    private volatile java.lang.Object memoryUsageRatio_;
    /**
     * <code>string memoryUsageRatio = 7;</code>
     */
    public java.lang.String getMemoryUsageRatio() {
      java.lang.Object ref = memoryUsageRatio_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        memoryUsageRatio_ = s;
        return s;
      }
    }
    /**
     * <code>string memoryUsageRatio = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMemoryUsageRatioBytes() {
      java.lang.Object ref = memoryUsageRatio_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memoryUsageRatio_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMORYFREE_FIELD_NUMBER = 8;
    private volatile java.lang.Object memoryFree_;
    /**
     * <code>string memoryFree = 8;</code>
     */
    public java.lang.String getMemoryFree() {
      java.lang.Object ref = memoryFree_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        memoryFree_ = s;
        return s;
      }
    }
    /**
     * <code>string memoryFree = 8;</code>
     */
    public com.google.protobuf.ByteString
        getMemoryFreeBytes() {
      java.lang.Object ref = memoryFree_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memoryFree_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMORYALLOCATED_FIELD_NUMBER = 9;
    private int memoryAllocated_;
    /**
     * <code>int32 memoryAllocated = 9;</code>
     */
    public int getMemoryAllocated() {
      return memoryAllocated_;
    }

    public static final int MEMORYTOTAL_FIELD_NUMBER = 10;
    private volatile java.lang.Object memoryTotal_;
    /**
     * <code>string memoryTotal = 10;</code>
     */
    public java.lang.String getMemoryTotal() {
      java.lang.Object ref = memoryTotal_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        memoryTotal_ = s;
        return s;
      }
    }
    /**
     * <code>string memoryTotal = 10;</code>
     */
    public com.google.protobuf.ByteString
        getMemoryTotalBytes() {
      java.lang.Object ref = memoryTotal_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memoryTotal_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISUSAGEMAP_FIELD_NUMBER = 11;
    private java.util.List<com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry> disUsageMap_;
    /**
     * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
     */
    public java.util.List<com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry> getDisUsageMapList() {
      return disUsageMap_;
    }
    /**
     * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
     */
    public java.util.List<? extends com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntryOrBuilder> 
        getDisUsageMapOrBuilderList() {
      return disUsageMap_;
    }
    /**
     * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
     */
    public int getDisUsageMapCount() {
      return disUsageMap_.size();
    }
    /**
     * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
     */
    public com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry getDisUsageMap(int index) {
      return disUsageMap_.get(index);
    }
    /**
     * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
     */
    public com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntryOrBuilder getDisUsageMapOrBuilder(
        int index) {
      return disUsageMap_.get(index);
    }

    public static final int CREATETIME_FIELD_NUMBER = 12;
    private long createTime_;
    /**
     * <code>int64 createTime = 12;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    public static final int MODIFYTIME_FIELD_NUMBER = 13;
    private long modifyTime_;
    /**
     * <code>int64 modifyTime = 13;</code>
     */
    public long getModifyTime() {
      return modifyTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (hostId_ != 0L) {
        output.writeInt64(2, hostId_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ip_);
      }
      if (!getCpuUsageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cpuUsage_);
      }
      if (!getLoadBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, load_);
      }
      if (!getTrafficBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, traffic_);
      }
      if (!getMemoryUsageRatioBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, memoryUsageRatio_);
      }
      if (!getMemoryFreeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, memoryFree_);
      }
      if (memoryAllocated_ != 0) {
        output.writeInt32(9, memoryAllocated_);
      }
      if (!getMemoryTotalBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, memoryTotal_);
      }
      for (int i = 0; i < disUsageMap_.size(); i++) {
        output.writeMessage(11, disUsageMap_.get(i));
      }
      if (createTime_ != 0L) {
        output.writeInt64(12, createTime_);
      }
      if (modifyTime_ != 0L) {
        output.writeInt64(13, modifyTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (hostId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, hostId_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ip_);
      }
      if (!getCpuUsageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cpuUsage_);
      }
      if (!getLoadBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, load_);
      }
      if (!getTrafficBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, traffic_);
      }
      if (!getMemoryUsageRatioBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, memoryUsageRatio_);
      }
      if (!getMemoryFreeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, memoryFree_);
      }
      if (memoryAllocated_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, memoryAllocated_);
      }
      if (!getMemoryTotalBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, memoryTotal_);
      }
      for (int i = 0; i < disUsageMap_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, disUsageMap_.get(i));
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, createTime_);
      }
      if (modifyTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(13, modifyTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gxf.udp.proto.MachineStat_Pb.MachineStat)) {
        return super.equals(obj);
      }
      com.gxf.udp.proto.MachineStat_Pb.MachineStat other = (com.gxf.udp.proto.MachineStat_Pb.MachineStat) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getHostId()
          == other.getHostId());
      result = result && getIp()
          .equals(other.getIp());
      result = result && getCpuUsage()
          .equals(other.getCpuUsage());
      result = result && getLoad()
          .equals(other.getLoad());
      result = result && getTraffic()
          .equals(other.getTraffic());
      result = result && getMemoryUsageRatio()
          .equals(other.getMemoryUsageRatio());
      result = result && getMemoryFree()
          .equals(other.getMemoryFree());
      result = result && (getMemoryAllocated()
          == other.getMemoryAllocated());
      result = result && getMemoryTotal()
          .equals(other.getMemoryTotal());
      result = result && getDisUsageMapList()
          .equals(other.getDisUsageMapList());
      result = result && (getCreateTime()
          == other.getCreateTime());
      result = result && (getModifyTime()
          == other.getModifyTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + HOSTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHostId());
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + CPUUSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getCpuUsage().hashCode();
      hash = (37 * hash) + LOAD_FIELD_NUMBER;
      hash = (53 * hash) + getLoad().hashCode();
      hash = (37 * hash) + TRAFFIC_FIELD_NUMBER;
      hash = (53 * hash) + getTraffic().hashCode();
      hash = (37 * hash) + MEMORYUSAGERATIO_FIELD_NUMBER;
      hash = (53 * hash) + getMemoryUsageRatio().hashCode();
      hash = (37 * hash) + MEMORYFREE_FIELD_NUMBER;
      hash = (53 * hash) + getMemoryFree().hashCode();
      hash = (37 * hash) + MEMORYALLOCATED_FIELD_NUMBER;
      hash = (53 * hash) + getMemoryAllocated();
      hash = (37 * hash) + MEMORYTOTAL_FIELD_NUMBER;
      hash = (53 * hash) + getMemoryTotal().hashCode();
      if (getDisUsageMapCount() > 0) {
        hash = (37 * hash) + DISUSAGEMAP_FIELD_NUMBER;
        hash = (53 * hash) + getDisUsageMapList().hashCode();
      }
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (37 * hash) + MODIFYTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getModifyTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gxf.udp.proto.MachineStat_Pb.MachineStat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.MachineStat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.MachineStat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.MachineStat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.MachineStat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.MachineStat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.MachineStat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.MachineStat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.MachineStat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.MachineStat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.MachineStat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.MachineStat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gxf.udp.proto.MachineStat_Pb.MachineStat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gxf.udp.proto.MachineStat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gxf.udp.proto.MachineStat)
        com.gxf.udp.proto.MachineStat_Pb.MachineStatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gxf.udp.proto.MachineStat_Pb.internal_static_com_gxf_udp_proto_MachineStat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gxf.udp.proto.MachineStat_Pb.internal_static_com_gxf_udp_proto_MachineStat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gxf.udp.proto.MachineStat_Pb.MachineStat.class, com.gxf.udp.proto.MachineStat_Pb.MachineStat.Builder.class);
      }

      // Construct using com.gxf.udp.proto.MachineStat_Pb.MachineStat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDisUsageMapFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        hostId_ = 0L;

        ip_ = "";

        cpuUsage_ = "";

        load_ = "";

        traffic_ = "";

        memoryUsageRatio_ = "";

        memoryFree_ = "";

        memoryAllocated_ = 0;

        memoryTotal_ = "";

        if (disUsageMapBuilder_ == null) {
          disUsageMap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000400);
        } else {
          disUsageMapBuilder_.clear();
        }
        createTime_ = 0L;

        modifyTime_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gxf.udp.proto.MachineStat_Pb.internal_static_com_gxf_udp_proto_MachineStat_descriptor;
      }

      public com.gxf.udp.proto.MachineStat_Pb.MachineStat getDefaultInstanceForType() {
        return com.gxf.udp.proto.MachineStat_Pb.MachineStat.getDefaultInstance();
      }

      public com.gxf.udp.proto.MachineStat_Pb.MachineStat build() {
        com.gxf.udp.proto.MachineStat_Pb.MachineStat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gxf.udp.proto.MachineStat_Pb.MachineStat buildPartial() {
        com.gxf.udp.proto.MachineStat_Pb.MachineStat result = new com.gxf.udp.proto.MachineStat_Pb.MachineStat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.hostId_ = hostId_;
        result.ip_ = ip_;
        result.cpuUsage_ = cpuUsage_;
        result.load_ = load_;
        result.traffic_ = traffic_;
        result.memoryUsageRatio_ = memoryUsageRatio_;
        result.memoryFree_ = memoryFree_;
        result.memoryAllocated_ = memoryAllocated_;
        result.memoryTotal_ = memoryTotal_;
        if (disUsageMapBuilder_ == null) {
          if (((bitField0_ & 0x00000400) == 0x00000400)) {
            disUsageMap_ = java.util.Collections.unmodifiableList(disUsageMap_);
            bitField0_ = (bitField0_ & ~0x00000400);
          }
          result.disUsageMap_ = disUsageMap_;
        } else {
          result.disUsageMap_ = disUsageMapBuilder_.build();
        }
        result.createTime_ = createTime_;
        result.modifyTime_ = modifyTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gxf.udp.proto.MachineStat_Pb.MachineStat) {
          return mergeFrom((com.gxf.udp.proto.MachineStat_Pb.MachineStat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gxf.udp.proto.MachineStat_Pb.MachineStat other) {
        if (other == com.gxf.udp.proto.MachineStat_Pb.MachineStat.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getHostId() != 0L) {
          setHostId(other.getHostId());
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (!other.getCpuUsage().isEmpty()) {
          cpuUsage_ = other.cpuUsage_;
          onChanged();
        }
        if (!other.getLoad().isEmpty()) {
          load_ = other.load_;
          onChanged();
        }
        if (!other.getTraffic().isEmpty()) {
          traffic_ = other.traffic_;
          onChanged();
        }
        if (!other.getMemoryUsageRatio().isEmpty()) {
          memoryUsageRatio_ = other.memoryUsageRatio_;
          onChanged();
        }
        if (!other.getMemoryFree().isEmpty()) {
          memoryFree_ = other.memoryFree_;
          onChanged();
        }
        if (other.getMemoryAllocated() != 0) {
          setMemoryAllocated(other.getMemoryAllocated());
        }
        if (!other.getMemoryTotal().isEmpty()) {
          memoryTotal_ = other.memoryTotal_;
          onChanged();
        }
        if (disUsageMapBuilder_ == null) {
          if (!other.disUsageMap_.isEmpty()) {
            if (disUsageMap_.isEmpty()) {
              disUsageMap_ = other.disUsageMap_;
              bitField0_ = (bitField0_ & ~0x00000400);
            } else {
              ensureDisUsageMapIsMutable();
              disUsageMap_.addAll(other.disUsageMap_);
            }
            onChanged();
          }
        } else {
          if (!other.disUsageMap_.isEmpty()) {
            if (disUsageMapBuilder_.isEmpty()) {
              disUsageMapBuilder_.dispose();
              disUsageMapBuilder_ = null;
              disUsageMap_ = other.disUsageMap_;
              bitField0_ = (bitField0_ & ~0x00000400);
              disUsageMapBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDisUsageMapFieldBuilder() : null;
            } else {
              disUsageMapBuilder_.addAllMessages(other.disUsageMap_);
            }
          }
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (other.getModifyTime() != 0L) {
          setModifyTime(other.getModifyTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gxf.udp.proto.MachineStat_Pb.MachineStat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gxf.udp.proto.MachineStat_Pb.MachineStat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long hostId_ ;
      /**
       * <code>int64 hostId = 2;</code>
       */
      public long getHostId() {
        return hostId_;
      }
      /**
       * <code>int64 hostId = 2;</code>
       */
      public Builder setHostId(long value) {
        
        hostId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 hostId = 2;</code>
       */
      public Builder clearHostId() {
        
        hostId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>string ip = 3;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 3;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 3;</code>
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 3;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cpuUsage_ = "";
      /**
       * <code>string cpuUsage = 4;</code>
       */
      public java.lang.String getCpuUsage() {
        java.lang.Object ref = cpuUsage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cpuUsage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cpuUsage = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCpuUsageBytes() {
        java.lang.Object ref = cpuUsage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cpuUsage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cpuUsage = 4;</code>
       */
      public Builder setCpuUsage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cpuUsage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cpuUsage = 4;</code>
       */
      public Builder clearCpuUsage() {
        
        cpuUsage_ = getDefaultInstance().getCpuUsage();
        onChanged();
        return this;
      }
      /**
       * <code>string cpuUsage = 4;</code>
       */
      public Builder setCpuUsageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cpuUsage_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object load_ = "";
      /**
       * <code>string load = 5;</code>
       */
      public java.lang.String getLoad() {
        java.lang.Object ref = load_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          load_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string load = 5;</code>
       */
      public com.google.protobuf.ByteString
          getLoadBytes() {
        java.lang.Object ref = load_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          load_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string load = 5;</code>
       */
      public Builder setLoad(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        load_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string load = 5;</code>
       */
      public Builder clearLoad() {
        
        load_ = getDefaultInstance().getLoad();
        onChanged();
        return this;
      }
      /**
       * <code>string load = 5;</code>
       */
      public Builder setLoadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        load_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object traffic_ = "";
      /**
       * <code>string traffic = 6;</code>
       */
      public java.lang.String getTraffic() {
        java.lang.Object ref = traffic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          traffic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string traffic = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTrafficBytes() {
        java.lang.Object ref = traffic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          traffic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string traffic = 6;</code>
       */
      public Builder setTraffic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        traffic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string traffic = 6;</code>
       */
      public Builder clearTraffic() {
        
        traffic_ = getDefaultInstance().getTraffic();
        onChanged();
        return this;
      }
      /**
       * <code>string traffic = 6;</code>
       */
      public Builder setTrafficBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        traffic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object memoryUsageRatio_ = "";
      /**
       * <code>string memoryUsageRatio = 7;</code>
       */
      public java.lang.String getMemoryUsageRatio() {
        java.lang.Object ref = memoryUsageRatio_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          memoryUsageRatio_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string memoryUsageRatio = 7;</code>
       */
      public com.google.protobuf.ByteString
          getMemoryUsageRatioBytes() {
        java.lang.Object ref = memoryUsageRatio_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          memoryUsageRatio_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string memoryUsageRatio = 7;</code>
       */
      public Builder setMemoryUsageRatio(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        memoryUsageRatio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string memoryUsageRatio = 7;</code>
       */
      public Builder clearMemoryUsageRatio() {
        
        memoryUsageRatio_ = getDefaultInstance().getMemoryUsageRatio();
        onChanged();
        return this;
      }
      /**
       * <code>string memoryUsageRatio = 7;</code>
       */
      public Builder setMemoryUsageRatioBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        memoryUsageRatio_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object memoryFree_ = "";
      /**
       * <code>string memoryFree = 8;</code>
       */
      public java.lang.String getMemoryFree() {
        java.lang.Object ref = memoryFree_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          memoryFree_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string memoryFree = 8;</code>
       */
      public com.google.protobuf.ByteString
          getMemoryFreeBytes() {
        java.lang.Object ref = memoryFree_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          memoryFree_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string memoryFree = 8;</code>
       */
      public Builder setMemoryFree(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        memoryFree_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string memoryFree = 8;</code>
       */
      public Builder clearMemoryFree() {
        
        memoryFree_ = getDefaultInstance().getMemoryFree();
        onChanged();
        return this;
      }
      /**
       * <code>string memoryFree = 8;</code>
       */
      public Builder setMemoryFreeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        memoryFree_ = value;
        onChanged();
        return this;
      }

      private int memoryAllocated_ ;
      /**
       * <code>int32 memoryAllocated = 9;</code>
       */
      public int getMemoryAllocated() {
        return memoryAllocated_;
      }
      /**
       * <code>int32 memoryAllocated = 9;</code>
       */
      public Builder setMemoryAllocated(int value) {
        
        memoryAllocated_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 memoryAllocated = 9;</code>
       */
      public Builder clearMemoryAllocated() {
        
        memoryAllocated_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object memoryTotal_ = "";
      /**
       * <code>string memoryTotal = 10;</code>
       */
      public java.lang.String getMemoryTotal() {
        java.lang.Object ref = memoryTotal_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          memoryTotal_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string memoryTotal = 10;</code>
       */
      public com.google.protobuf.ByteString
          getMemoryTotalBytes() {
        java.lang.Object ref = memoryTotal_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          memoryTotal_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string memoryTotal = 10;</code>
       */
      public Builder setMemoryTotal(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        memoryTotal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string memoryTotal = 10;</code>
       */
      public Builder clearMemoryTotal() {
        
        memoryTotal_ = getDefaultInstance().getMemoryTotal();
        onChanged();
        return this;
      }
      /**
       * <code>string memoryTotal = 10;</code>
       */
      public Builder setMemoryTotalBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        memoryTotal_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry> disUsageMap_ =
        java.util.Collections.emptyList();
      private void ensureDisUsageMapIsMutable() {
        if (!((bitField0_ & 0x00000400) == 0x00000400)) {
          disUsageMap_ = new java.util.ArrayList<com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry>(disUsageMap_);
          bitField0_ |= 0x00000400;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry, com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.Builder, com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntryOrBuilder> disUsageMapBuilder_;

      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public java.util.List<com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry> getDisUsageMapList() {
        if (disUsageMapBuilder_ == null) {
          return java.util.Collections.unmodifiableList(disUsageMap_);
        } else {
          return disUsageMapBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public int getDisUsageMapCount() {
        if (disUsageMapBuilder_ == null) {
          return disUsageMap_.size();
        } else {
          return disUsageMapBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry getDisUsageMap(int index) {
        if (disUsageMapBuilder_ == null) {
          return disUsageMap_.get(index);
        } else {
          return disUsageMapBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public Builder setDisUsageMap(
          int index, com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry value) {
        if (disUsageMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDisUsageMapIsMutable();
          disUsageMap_.set(index, value);
          onChanged();
        } else {
          disUsageMapBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public Builder setDisUsageMap(
          int index, com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.Builder builderForValue) {
        if (disUsageMapBuilder_ == null) {
          ensureDisUsageMapIsMutable();
          disUsageMap_.set(index, builderForValue.build());
          onChanged();
        } else {
          disUsageMapBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public Builder addDisUsageMap(com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry value) {
        if (disUsageMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDisUsageMapIsMutable();
          disUsageMap_.add(value);
          onChanged();
        } else {
          disUsageMapBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public Builder addDisUsageMap(
          int index, com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry value) {
        if (disUsageMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDisUsageMapIsMutable();
          disUsageMap_.add(index, value);
          onChanged();
        } else {
          disUsageMapBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public Builder addDisUsageMap(
          com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.Builder builderForValue) {
        if (disUsageMapBuilder_ == null) {
          ensureDisUsageMapIsMutable();
          disUsageMap_.add(builderForValue.build());
          onChanged();
        } else {
          disUsageMapBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public Builder addDisUsageMap(
          int index, com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.Builder builderForValue) {
        if (disUsageMapBuilder_ == null) {
          ensureDisUsageMapIsMutable();
          disUsageMap_.add(index, builderForValue.build());
          onChanged();
        } else {
          disUsageMapBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public Builder addAllDisUsageMap(
          java.lang.Iterable<? extends com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry> values) {
        if (disUsageMapBuilder_ == null) {
          ensureDisUsageMapIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, disUsageMap_);
          onChanged();
        } else {
          disUsageMapBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public Builder clearDisUsageMap() {
        if (disUsageMapBuilder_ == null) {
          disUsageMap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000400);
          onChanged();
        } else {
          disUsageMapBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public Builder removeDisUsageMap(int index) {
        if (disUsageMapBuilder_ == null) {
          ensureDisUsageMapIsMutable();
          disUsageMap_.remove(index);
          onChanged();
        } else {
          disUsageMapBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.Builder getDisUsageMapBuilder(
          int index) {
        return getDisUsageMapFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntryOrBuilder getDisUsageMapOrBuilder(
          int index) {
        if (disUsageMapBuilder_ == null) {
          return disUsageMap_.get(index);  } else {
          return disUsageMapBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public java.util.List<? extends com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntryOrBuilder> 
           getDisUsageMapOrBuilderList() {
        if (disUsageMapBuilder_ != null) {
          return disUsageMapBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(disUsageMap_);
        }
      }
      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.Builder addDisUsageMapBuilder() {
        return getDisUsageMapFieldBuilder().addBuilder(
            com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.Builder addDisUsageMapBuilder(
          int index) {
        return getDisUsageMapFieldBuilder().addBuilder(
            index, com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .com.gxf.udp.proto.DiskUsageMapFileEntry disUsageMap = 11;</code>
       */
      public java.util.List<com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.Builder> 
           getDisUsageMapBuilderList() {
        return getDisUsageMapFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry, com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.Builder, com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntryOrBuilder> 
          getDisUsageMapFieldBuilder() {
        if (disUsageMapBuilder_ == null) {
          disUsageMapBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry, com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.Builder, com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntryOrBuilder>(
                  disUsageMap_,
                  ((bitField0_ & 0x00000400) == 0x00000400),
                  getParentForChildren(),
                  isClean());
          disUsageMap_ = null;
        }
        return disUsageMapBuilder_;
      }

      private long createTime_ ;
      /**
       * <code>int64 createTime = 12;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>int64 createTime = 12;</code>
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 createTime = 12;</code>
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private long modifyTime_ ;
      /**
       * <code>int64 modifyTime = 13;</code>
       */
      public long getModifyTime() {
        return modifyTime_;
      }
      /**
       * <code>int64 modifyTime = 13;</code>
       */
      public Builder setModifyTime(long value) {
        
        modifyTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 modifyTime = 13;</code>
       */
      public Builder clearModifyTime() {
        
        modifyTime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.gxf.udp.proto.MachineStat)
    }

    // @@protoc_insertion_point(class_scope:com.gxf.udp.proto.MachineStat)
    private static final com.gxf.udp.proto.MachineStat_Pb.MachineStat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gxf.udp.proto.MachineStat_Pb.MachineStat();
    }

    public static com.gxf.udp.proto.MachineStat_Pb.MachineStat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MachineStat>
        PARSER = new com.google.protobuf.AbstractParser<MachineStat>() {
      public MachineStat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MachineStat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MachineStat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MachineStat> getParserForType() {
      return PARSER;
    }

    public com.gxf.udp.proto.MachineStat_Pb.MachineStat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DiskUsageMapFileEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gxf.udp.proto.DiskUsageMapFileEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code com.gxf.udp.proto.DiskUsageMapFileEntry}
   */
  public  static final class DiskUsageMapFileEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gxf.udp.proto.DiskUsageMapFileEntry)
      DiskUsageMapFileEntryOrBuilder {
    // Use DiskUsageMapFileEntry.newBuilder() to construct.
    private DiskUsageMapFileEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DiskUsageMapFileEntry() {
      key_ = "";
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DiskUsageMapFileEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gxf.udp.proto.MachineStat_Pb.internal_static_com_gxf_udp_proto_DiskUsageMapFileEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gxf.udp.proto.MachineStat_Pb.internal_static_com_gxf_udp_proto_DiskUsageMapFileEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.class, com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry)) {
        return super.equals(obj);
      }
      com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry other = (com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry) obj;

      boolean result = true;
      result = result && getKey()
          .equals(other.getKey());
      result = result && getValue()
          .equals(other.getValue());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gxf.udp.proto.DiskUsageMapFileEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gxf.udp.proto.DiskUsageMapFileEntry)
        com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gxf.udp.proto.MachineStat_Pb.internal_static_com_gxf_udp_proto_DiskUsageMapFileEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gxf.udp.proto.MachineStat_Pb.internal_static_com_gxf_udp_proto_DiskUsageMapFileEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.class, com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.Builder.class);
      }

      // Construct using com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        key_ = "";

        value_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gxf.udp.proto.MachineStat_Pb.internal_static_com_gxf_udp_proto_DiskUsageMapFileEntry_descriptor;
      }

      public com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry getDefaultInstanceForType() {
        return com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.getDefaultInstance();
      }

      public com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry build() {
        com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry buildPartial() {
        com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry result = new com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry(this);
        result.key_ = key_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry) {
          return mergeFrom((com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry other) {
        if (other == com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.gxf.udp.proto.DiskUsageMapFileEntry)
    }

    // @@protoc_insertion_point(class_scope:com.gxf.udp.proto.DiskUsageMapFileEntry)
    private static final com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry();
    }

    public static com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DiskUsageMapFileEntry>
        PARSER = new com.google.protobuf.AbstractParser<DiskUsageMapFileEntry>() {
      public DiskUsageMapFileEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DiskUsageMapFileEntry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DiskUsageMapFileEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DiskUsageMapFileEntry> getParserForType() {
      return PARSER;
    }

    public com.gxf.udp.proto.MachineStat_Pb.DiskUsageMapFileEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gxf_udp_proto_MachineStat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gxf_udp_proto_MachineStat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gxf_udp_proto_DiskUsageMapFileEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gxf_udp_proto_DiskUsageMapFileEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MachineStat.proto\022\021com.gxf.udp.proto\"\251" +
      "\002\n\013MachineStat\022\n\n\002id\030\001 \001(\003\022\016\n\006hostId\030\002 \001" +
      "(\003\022\n\n\002ip\030\003 \001(\t\022\020\n\010cpuUsage\030\004 \001(\t\022\014\n\004load" +
      "\030\005 \001(\t\022\017\n\007traffic\030\006 \001(\t\022\030\n\020memoryUsageRa" +
      "tio\030\007 \001(\t\022\022\n\nmemoryFree\030\010 \001(\t\022\027\n\017memoryA" +
      "llocated\030\t \001(\005\022\023\n\013memoryTotal\030\n \001(\t\022=\n\013d" +
      "isUsageMap\030\013 \003(\0132(.com.gxf.udp.proto.Dis" +
      "kUsageMapFileEntry\022\022\n\ncreateTime\030\014 \001(\003\022\022" +
      "\n\nmodifyTime\030\r \001(\003\"3\n\025DiskUsageMapFileEn" +
      "try\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\tB\020B\016Machi",
      "neStat_Pbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_gxf_udp_proto_MachineStat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gxf_udp_proto_MachineStat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gxf_udp_proto_MachineStat_descriptor,
        new java.lang.String[] { "Id", "HostId", "Ip", "CpuUsage", "Load", "Traffic", "MemoryUsageRatio", "MemoryFree", "MemoryAllocated", "MemoryTotal", "DisUsageMap", "CreateTime", "ModifyTime", });
    internal_static_com_gxf_udp_proto_DiskUsageMapFileEntry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gxf_udp_proto_DiskUsageMapFileEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gxf_udp_proto_DiskUsageMapFileEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
